### ISSUE TITLE
Google App Engine failure

### ISSUE THREAD

**Issue by 17twenty** [lionelbarrow/braintree-go#49] opened 2015-10-25 05:02 UTC
Trying to use the library from within Google App Engine yields a failure:
```
Fatal errorPost https://sandbox.braintreegateway.com/merchants/XXX/customers: http.DefaultTransport and http.DefaultClient are not available in App Engine. See https://cloud.google.com/appengine/docs/go/urlfetch/
```

It looks like using those calls are considered bad (same issue fixed in the OAuth library https://github.com/golang/oauth2/issues/27 ). 

Are you able to pitch a fix for that particular issue? I can help with testing if need be

**Comment by 17twenty** [comment] 2015-10-25 05:41
I added a new function to braintree.go, it would be nicer to get it to support a passed transport but I needed a quick and dirty solution.
appengine/urlfetch does provide a compatible transport so this worked fine for me - see https://cloud.google.com/appengine/docs/go/urlfetch/ for info.

```
func NewWithGAEContext(env Environment, merchId, pubKey, privKey string, gaeCtx *appengine.Context) *Braintree {

	return &Braintree{
		Environment: env,
		MerchantId:  merchId,
		PublicKey:   pubKey,
		PrivateKey:  privKey,
		ctx:  gaeCtx,
	}
}

type Braintree struct {
	Environment Environment
	MerchantId  string
	PublicKey   string
	PrivateKey  string
	Logger      *log.Logger
	HttpClient  *http.Client
	ctx *appengine.Context
}

func (g *Braintree) MerchantURL() string {
	return g.Environment.BaseURL() + "/merchants/" + g.MerchantId
}

func (g *Braintree) execute(method, path string, xmlObj interface{}) (*Response, error) {
	var buf bytes.Buffer
	if xmlObj != nil {
		xmlBody, err := xml.Marshal(xmlObj)
		if err != nil {
			return nil, err
		}
		_, err = buf.Write(xmlBody)
		if err != nil {
			return nil, err
		}
	}

	url := g.MerchantURL() + "/" + path

	if g.Logger != nil {
		g.Logger.Printf("> %s %s\n%s", method, url, buf.String())
	}

	req, err := http.NewRequest(method, url, &buf)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/xml")
	req.Header.Set("Accept", "application/xml")
	req.Header.Set("Accept-Encoding", "gzip")
	req.Header.Set("User-Agent", fmt.Sprintf("Braintree Go %s", LibraryVersion))
	req.Header.Set("X-ApiVersion", "3")
	req.SetBasicAuth(g.PublicKey, g.PrivateKey)

	httpClient := g.HttpClient

	if g.ctx != nil {
		httpClient = urlfetch.Client(*g.ctx)
	} else {
		if httpClient == nil {
			httpClient = http.DefaultClient
		}
	}
...
```

How would you like to see something like this added?

**Comment by lionelbarrow** [comment] 2015-10-30 20:11
Yea, if the issue is that we can't use the default HTTP client, making it injectable with a sane default is a really good idea.

**Comment by pedromg** [comment] 2015-10-31 15:54
bt := braintree.New(
		BrainTreeEnvironment,
		theProvider.Braintree.MerchantId,
		theProvider.Braintree.PublicKey,
		theProvider.Braintree.PrivateKey,
	)

	// set the context
	bt.SetHTTPClient(urlfetch.Client(context))

	return bt, nil

**Comment by pedromg** [comment] 2015-10-31 15:57
I've been using this successfully:

```
// SetHTTPClient overrides the default HTTP client.
// This is useful if you're running in a Google AppEngine environment
// where the http.DefaultClient is not available.
// eg: g.SetHTTPClient(urlfetch.Client(appengine.NewContext(req)))
func (g *Braintree) SetHTTPClient(client *http.Client) {
	g.HttpClient = client
}
```

Now one can use AppEngine requests, having ```context context.Context```:

```
	bt := braintree.New(
		BrainTreeEnvironment,
		theProvider.Braintree.MerchantId,
		theProvider.Braintree.PublicKey,
		theProvider.Braintree.PrivateKey,
	)

	// set the context
	bt.SetHTTPClient(urlfetch.Client(context))
```

**Comment by dakom** [comment] 2016-06-05 13:08
@pedromg that's a really good idea. In the meantime, until that's merged into the main branch, I don't think there's anything wrong with setting it directly on the object, is there?

i.e. `bt := braintree.New() [...] bt.HttpClient = utlfetch.Client(context)`

**Comment by lionelbarrow** [comment] 2016-06-26 17:07
@dakom Nope, although it'd be better form to have it in the constructor, so I've just added one: `NewWithHttpClient`, that allows you to set the client directly at creation time.

**Closed by lionelbarrow** 2016-06-26 17:07 UTC
